name: Build
on:
  - push
  - pull_request

jobs:
  build-python:
    uses: goes-funky/workflows/.github/workflows/build-python.yaml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      python-version: "3.9"
      poetry-version: "1.3.2"
      is-repo-public: true
      skip-mypy: true
      skip-tests: false
      skip-isort: true
      skip-format: true
      skip-lint: true
      skip-sonar: false
